name: Generate Bookmarks

on:
  push:
    branches:
      - main

jobs:
  generate-bookmarks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install -g uglify-js
        sudo apt-get install jq

    - name: Generate bookmarks JSON
      run: |
        mkdir -p output
        echo "{}" > output/bookmarks.json
        for file in bookmarklets/*.js; do
          name=$(basename "$file" .js)
          bookmarklet=$(./bookmarklify.sh "$file")
          jq --arg name "$name" --arg bookmarklet "$bookmarklet" '.[$name] = $bookmarklet' output/bookmarks.json > temp.json && mv temp.json output/bookmarks.json
        done

    - name: Generate importable HTML
      run: |
        echo "<DL><p>" > output/bookmarks.html
        jq -r 'to_entries[] | "<DT><A HREF=\"\(.value)\">\(.key)</A>"' output/bookmarks.json >> output/bookmarks.html
        echo "</DL><p>" >> output/bookmarks.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bookmarks
        path: output/
